analyze_prompt:
  description: >
    Summarize the business requirements from the input prompt: 
    {customer_prompt}.

    Identify all the criteria for a potential lead. List the criteria clearly, specifically and easily understood.

    Write the result into a file called "customer_prompt_result.txt" in the "transcript_analytics_crew" folder. This is provided by the tool.

    IMPORTANT: Format the output as a valid JSON array of criteria objects, each with 'name' and 'description' fields.

  expected_output: >
    A valid JSON array of criteria objects.
  agent: prompt_analyzer_agent

evaluate_transcript:
  description: >
    Analyze call transcripts {transcripts} and assess whether leads meet each defined criteria in "customer_prompt_result.txt". Provide clear conclusions and rationale.
    Then conclution pass status if lead meet equal or more than 60% of the criteria defined.
    Write the result into a file called "transcript_result.txt" in the "transcript_analytics_crew" folder. This is provided by the tool.

    IMPORTANT: Format your response as a valid JSON object with the following structure:
    {
      "pass": boolean,
      "criteria_results": [
        {
          "criterion": "criterion name",
          "passed": boolean,
          "reason": "explanation"
        },
        ...
      ]
    }

    NOTE: - lead pass condition: "pass" field willSet to true if equal or more than 60% of the criteria have passed

  expected_output: >
    A valid JSON object with pass status and detailed criteria results.
  agent: transcript_analyzer_agent
